### ISSUE TITLE
Once enabled, sound cannot be disabled

### ISSUE THREAD

**Issue by xoner2** [mudar/SnooZy#19]
Sound is disabled by default. Once you've selected a sound file, you can't set it back to "None". Clicking on "Sound" goes to file selection.

**Comment by mudar** [comment]
hmm... that's strange. What device (OS) are you using? Usually "Silent" option is at the top of sound selection.

It could also be related to default apps: if sound selection opens with a file explorer instead of the system's sound selector, then I can see how you cannot set it back to silent ! In this case you can try resetting the sound selection default app..

**Comment by xoner2** [comment]
Oh right. My mistake. I mistook the sound selection app as file selection. Didn't see the "None".

Issue closed.
